# Generated by Django 5.2.1 on 2025-05-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="video",
        ),
    ]
