# Generated by Django 5.2.1 on 2025-05-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConversationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_message", models.TextField()),
                ("assistant_response", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("thread_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="llm_convers_timesta_649c43_idx"
                    ),
                    models.Index(
                        fields=["thread_id"], name="llm_convers_thread__3687fa_idx"
                    ),
                ],
            },
        ),
    ]
