# Generated by Django 5.2 on 2025-05-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_monetize_posts',
            field=models.BooleanField(default=False, verbose_name='Может монетизировать посты'),
        ),
    ]
