# Generated by Django 5.2 on 2025-05-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_can_monetize_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level_score',
            field=models.IntegerField(default=0, verbose_name='Общий уровень/ранк'),
        ),
        migrations.AddField(
            model_name='profile',
            name='levels_last_calculated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего расчета уровней'),
        ),
    ]
