# .github/workflows/deploy.yml
name: Deploy App to Droplet

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'my-vue-app/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH Key File and Known Hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          DROPLET_HOST: 139.59.64.140
        run: |
          mkdir -p ~/.ssh/
          chmod 700 ~/.ssh/
          KEY_FILE_PATH=~/.ssh/id_rsa_deploy
          printf "%s\n" "${SSH_PRIVATE_KEY}" > ${KEY_FILE_PATH}
          chmod 600 ${KEY_FILE_PATH}
          if ! ssh-keygen -l -f ${KEY_FILE_PATH} > /dev/null 2>&1; then
            echo "❌ ERROR: Invalid SSH key format detected in secret." >&2
            exit 1
          fi
          ssh-keyscan -H "${DROPLET_HOST}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to Droplet
        env:
          DROPLET_HOST: 139.59.64.140
          DROPLET_USER: root
          BACKEND_DEPLOY_DIR: /root/app/backend
          FRONTEND_DEPLOY_DIR: /root/app/my-vue-app
          # --- Django & DB Secrets/Config ---
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: fitness_db
          DB_USER: postgres
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }} 
          # --- AWS S3 Secrets/Config ---
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
          AWS_S3_REGION_NAME: ${{ secrets.AWS_S3_REGION_NAME }}
          AWS_DEFAULT_ACL: 'private'
          AWS_LOCATION: 'media'
          # --- OpenAI Secrets ---
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ASSISTANT_ID: ${{ secrets.ASSISTANT_ID }}
        run: |
          KEY_FILE_PATH=~/.ssh/id_rsa_deploy

          # Создаем базовую директорию и директории для фронтенда и бэкенда на Droplet
          ssh -o StrictHostKeyChecking=no -i ${KEY_FILE_PATH} "${DROPLET_USER}@${DROPLET_HOST}" "mkdir -p ${BACKEND_DEPLOY_DIR} && mkdir -p ${FRONTEND_DEPLOY_DIR}"
          
          echo "Copying backend files to Droplet..."
          scp -r -o StrictHostKeyChecking=no -i ${KEY_FILE_PATH} ./backend/* "${DROPLET_USER}@${DROPLET_HOST}:${BACKEND_DEPLOY_DIR}/"
          echo "Backend files copied."

          echo "Copying frontend files to Droplet..."
          scp -r -o StrictHostKeyChecking=no -i ${KEY_FILE_PATH} ./my-vue-app/* "${DROPLET_USER}@${DROPLET_HOST}:${FRONTEND_DEPLOY_DIR}/"
          echo "Frontend files copied."

          # Подключаемся к Droplet и выполняем команды docker-compose из папки backend
          ssh -o StrictHostKeyChecking=no -i ${KEY_FILE_PATH} "${DROPLET_USER}@${DROPLET_HOST}" << EOF
            echo "Connected to Droplet. Running deployment commands..."
            cd ${BACKEND_DEPLOY_DIR} # Переходим в директорию бэкенда, где лежит docker-compose.prod.yml

            export SECRET_KEY='${{ env.SECRET_KEY }}'
            export DEBUG='False'
            export DB_PASSWORD='${{ env.DB_PASSWORD }}'
            export DB_NAME='${{ env.DB_NAME }}'
            export DB_USER='${{ env.DB_USER }}'
            export DB_HOST=db
            export EMAIL_HOST_PASSWORD='${{ env.EMAIL_HOST_PASSWORD }}'
            export AWS_ACCESS_KEY_ID='${{ env.AWS_ACCESS_KEY_ID }}'
            export AWS_SECRET_ACCESS_KEY='${{ env.AWS_SECRET_ACCESS_KEY }}'
            export AWS_STORAGE_BUCKET_NAME='${{ env.AWS_STORAGE_BUCKET_NAME }}'
            export AWS_S3_REGION_NAME='${{ env.AWS_S3_REGION_NAME }}'
            export AWS_DEFAULT_ACL='${{ env.AWS_DEFAULT_ACL }}'
            export AWS_LOCATION='${{ env.AWS_LOCATION }}'
            export OPENAI_API_KEY='${{ env.OPENAI_API_KEY }}'
            export ASSISTANT_ID='${{ env.ASSISTANT_ID }}'

            COMPOSE_FILE="docker-compose.prod.yml"
            if [ ! -f "\${COMPOSE_FILE}" ]; then
              echo "ERROR: \${COMPOSE_FILE} not found in ${BACKEND_DEPLOY_DIR}!"
              exit 1
            fi
            echo "Using \${COMPOSE_FILE}"

            docker compose -f \${COMPOSE_FILE} down --remove-orphans || echo "Docker down failed or no containers running."
            echo "Pulling base images..."
            docker compose -f \${COMPOSE_FILE} pull # Pulls all defined service images (db, redis, nginx base)
            echo "Building application images..."
            docker compose -f \${COMPOSE_FILE} build # Builds backend and frontend
            echo "Starting all containers..."
            docker compose -f \${COMPOSE_FILE} up -d
            
            echo "Cleaning up old docker images..."
            docker image prune -f || echo "Image prune failed."
            echo "Deployment script finished on Droplet."
          EOF
          echo "Deployment process complete."