name: Test S3 Connectivity from Actions

on:
  workflow_dispatch: # Ручной запуск

jobs:
  test-s3:
    runs-on: ubuntu-latest
    name: Check S3 Access

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_S3_REGION_NAME || 'eu-north-1' }} # Используем секрет или значение по умолчанию

      - name: List S3 Buckets (Basic Check)
        run: |
          echo "Attempting to list S3 buckets..."
          if aws s3 ls; then
            echo "✅ Successfully listed S3 buckets (basic credential check passed)."
          else
            echo "❌ ERROR: Failed to list S3 buckets."
            exit 1
          fi

      - name: Test Access to Specific Bucket
        env:
          BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
        run: |
          echo "Attempting to list contents of bucket: s3://${BUCKET_NAME}/"
          # Пытаемся вывести первые несколько объектов или просто проверить доступ
          if aws s3 ls "s3://${BUCKET_NAME}/" --page-size 5; then
             echo "✅ Successfully accessed bucket s3://${BUCKET_NAME}/"
          else
             echo "❌ ERROR: Failed to access bucket s3://${BUCKET_NAME}/. Check bucket name and IAM permissions."
             # Дополнительно можно попробовать загрузить тестовый файл
             # echo "Attempting to upload a test file..."
             # echo "test" > test.txt
             # if aws s3 cp test.txt "s3://${BUCKET_NAME}/github_actions_test.txt"; then
             #    echo "✅ Test file uploaded successfully."
             #    aws s3 rm "s3://${BUCKET_NAME}/github_actions_test.txt" # Удаляем тестовый файл
             # else
             #    echo "❌ ERROR: Failed to upload test file to s3://${BUCKET_NAME}/."
             #    exit 1
             # fi
             exit 1
          fi